#include "ti_msp_dl_config.h"
#include "Motor.h"
#include "Encoder.h"
#include "Delay.h"
#include "Tracking.h"
#include "Display.h"
#include "InertialNav.h"

/*
 * Main application entry.
 * Hardware pin setup is generated by SysConfig in SYSCFG_DL_init().
 * The while loop then runs one navigation-control cycle about every 10 ms.
 */
int main(void)
{
    SYSCFG_DL_init();

    /* Bring each software module into a known safe state before moving. */
    Motor_Init();
    Encoder_Init();
    Tracking_Init();
    NAV_Init();
    Display_Init();

    while (1) {
        /* Read sensors and decide line-follow, straight-run, or gyro turn. */
        NAV_ControlStep();

        /* Encoder speed is measured over this fixed sampling window. */
        Delay_ms(ENCODER_SAMPLE_MS);
        Encoder_Update();

        /* OLED is internally rate-limited so this can be called every loop. */
        Display_Update();

        /* Heartbeat LED: useful to confirm that the main loop is alive. */
        DL_GPIO_togglePins(RUN_LED_PORT, RUN_LED_LED_PIN);
    }
}
